
print (""" Enter
           + Addition
           - Substraction
           * mutiplication
           / division""")print("""   ENTER + FOR Addition
            ENTER - FOR Subtraction
            Enter * for multiplication
            Enter / for division""");
a= (input("Enter the operation wants to perform:- "))
x= int(input ("Enter the first numer:-  "));
y= int(input ("Enter the second numer:- "));
 
if a == "+";
     print(x+y);
else
    print("invalid");
a= int( input ("Ente the  1st number :-" ))
b= int( input ("Ente the  2nd number :-" ))
opr= input("enter the operator :-")
if opr =="+":
    print(a+b)
elif opr=="-":
    print(a-b)
elif opr=="*":
    print(a*b)
elif opr=="/":
    print(a/b)
else:
    print("Invalid operator");